import { readFileSync, readdirSync, statSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, it, expect } from 'vitest'

// __filename used in T24 below to resolve the i18n dir.

const __filename = fileURLToPath(import.meta.url)
const here = dirname(__filename)
const ROOT = join(here, '..')

function listSources(dir: string): string[] {
  const out: string[] = []
  for (const e of readdirSync(dir)) {
    if (e === '__tests__' || e === 'node_modules') continue
    const p = join(dir, e)
    const s = statSync(p)
    if (s.isDirectory()) out.push(...listSources(p))
    else if (e.endsWith('.tsx') || e.endsWith('.ts')) out.push(p)
  }
  return out
}
function stripComments(src: string): string {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|[^:])\/\/[^\n]*/g, '$1')
}

const sources = listSources(ROOT)
const corpus  = sources.map(p => ({
  path: p,
  src: readFileSync(p, 'utf8'),
  code: stripComments(readFileSync(p, 'utf8')),
}))

describe('CP3.3 — Team-Based Role Definition divergence UI', () => {
  // ============ T19 — DivergencePanel uses the audited compute RPC ============
  it('[T19] DivergencePanel imports computeDivergence and calls it on mount', () => {
    const panel = corpus.find(c => c.path.endsWith('DivergencePanel.tsx'))
    expect(panel, 'DivergencePanel.tsx must exist').toBeTruthy()
    const s = panel!.code
    expect(s).toMatch(/import\s*\{[^}]*\bcomputeDivergence\b/)
    expect(s).toMatch(/computeDivergence\(supabase,\s*run\.id\)/)
    // Triggered via useEffect on reload — not on a button-only path,
    // because the audit row is generated by rpc_compute_divergence itself
    // and the panel only renders post-seal stages.
    expect(s).toMatch(/useEffect\([^,]+,\s*\[\s*reload\s*\]\s*\)/)
  })

  // ============ T20 — DivergenceItem renders per-evaluator markers, not a single aggregate ============
  it('[T20] DivergenceItem renders one marker per evaluator value (positions surfaced, not averaged)', () => {
    const item = corpus.find(c => c.path.endsWith('DivergenceItem.tsx'))!
    const s = item.code
    // The dot-plot iteration: criterion.values.map((v, i) => ...)
    expect(s).toMatch(/criterion\.values\.map\(/)
    // The marker is identified by data-test attribute for downstream tests.
    expect(s).toMatch(/data-test="divergence-marker"/)
    // The mean appears only in a stats footer, not as the primary visual.
    // Specifically, the mean should not be the marker on the axis.
    const meanInMarker = /style=\{\{[^}]*criterion\.mean[^}]*\}\}\s*\/>/.test(s)
    expect(meanInMarker, 'criterion.mean must not be used as the marker position').toBe(false)
  })

  // ============ T21 — No single-aggregate framing in module copy ============
  it('[T21] Module body copy never frames the score as "the average is X" / "team thinks X" (surfacing principle)', () => {
    const offenders: string[] = []
    for (const { path, code } of corpus) {
      if (path.includes('__tests__')) continue
      const badPatterns = [
        /\bthe average is\b/i,
        /\bteam thinks\b/i,
        /\bwe averaged to\b/i,
        /\baveraged together\b/i,
      ]
      for (const p of badPatterns) {
        const m = code.match(p)
        if (m) offenders.push(path + ': ' + m[0])
      }
    }
    expect(offenders, `Single-aggregate framings leaked into UI copy: ${offenders.join(' | ')}`).toEqual([])
  })

  // ============ T22 — Anonymization defaults to OFF (E-codes, not names) ============
  it('[T22] DivergencePanel initialises showNames=false (E-codes by default, names only by toggle)', () => {
    const panel = corpus.find(c => c.path.endsWith('DivergencePanel.tsx'))!.code
    expect(panel).toMatch(/useState\((\s|<\s*boolean\s*>)?\s*false\s*\)\s*;?\s*\/?\/?/) // any boolean useState(false)
    expect(panel).toMatch(/showNames/)
    expect(panel).not.toMatch(/useState\(true\)/)  // No useState(true) — would default to revealed
  })

  // ============ T23 — EvaluatorRoster respects allow_attribution_on_reveal at render time ============
  it('[T23] EvaluatorRoster only reveals names when BOTH the toggle AND per-evaluator consent allow', () => {
    const roster = corpus.find(c => c.path.endsWith('EvaluatorRoster.tsx'))!.code
    expect(roster).toMatch(/showNames\s*&&\s*ev\.allow_attribution_on_reveal/)
    // The fallback when reveal is blocked is the literal string 'Anonymous'.
    expect(roster).toMatch(/['"]Anonymous['"]/)
  })

  // ============ T24 — read-during-seal count is wired AND surfaced via i18n ============
  it('[T24] DivergencePanel wires attemptedReadCount through to SealCallout AND en.json surfaces it', () => {
    const panel = corpus.find(c => c.path.endsWith('DivergencePanel.tsx'))!.code
    expect(panel).toMatch(/<SealCallout\b[^>]*attemptedReadCount=\{attemptedReadCount\}/)
    const seal = corpus.find(c => c.path.endsWith('SealCallout.tsx'))!.code
    expect(seal).toMatch(/attemptedReadCount/)
    // The 'team_def.read_during_seal' audit action label now lives in
    // i18n (en.json seal.body_unclean_html) — that's where the user-facing
    // surface comes from, so the test pivots to the dictionary.
    const en = JSON.parse(readFileSync(join(__filename.replace('cp33-divergence-ui.test.ts',''), '..', '..', '..', 'i18n', 'en.json'), 'utf8')) as Record<string, string>
    expect(en['seal.body_unclean_html']).toMatch(/team_def\.read_during_seal/)
  })

  // ============ T25 — RunHeader still doesn't drift on the surveillance framing ============
  it('[T25] No team-definition source frames Stage 2 sealing as optional (e.g. "you can preview", "peek")', () => {
    const offenders: string[] = []
    for (const { path, src } of corpus) {
      if (path.includes('__tests__')) continue
      if (/\byou can preview\b/i.test(src) || /\bpeek at\b/i.test(src) || /\bpreview ratings\b/i.test(src)) {
        offenders.push(path)
      }
    }
    expect(offenders, `Drift framings on sealing: ${offenders.join(' | ')}`).toEqual([])
  })
})
