-- phase3_step1_lifecycle_tables — the 7 module tables Phase 3 needs.
--
-- DEFAULT-DENY RLS on every table. EVERY visibility predicate is gated by
-- consent_active(_, 'ongoing_management') OR is_self() — never a membership
-- alone (per PHASE0 §4.4) and never a different consent purpose.
--
-- Two principles structurally enforced here:
--   * Developmental, never surveillance — every personal-data table carries
--     a self-read leg (the employee can see what the manager sees) AND the
--     four-quadrant signal labels are framed developmentally (growth_gap,
--     flight_risk, etc. — never "underperforming"). Hidden manager-only
--     scoring is impossible because the RLS self-leg cannot be turned off.
--   * Grounded, never fabricated — guidance_items.framework_ids is a
--     uuid[] with a CHECK requiring at least one citation. The DEV-STUB
--     seam matches Phase 1 + Phase 2: validity_status + _dev_stub +
--     refusal of 'validated' rows that carry stub values.

-- Enums for the new domain language.
create type public.refit_quadrant as enum (
  'stable_fit', 'growth_gap', 'flight_risk', 'emerging_misfit'
);
comment on type public.refit_quadrant is
  'Four-quadrant re-fit signal — developmental framing, never deficit-based.';

create type public.guidance_kind as enum (
  'one_on_one_prep', 'growth_focus', 'check_in_design', 'team_gap_callout'
);

create type public.guidance_action as enum (
  'acted_on', 'noted', 'snoozed', 'dismissed'
);

create type public.outcome_kind as enum (
  'promoted', 'lateral_move', 'role_change', 'left_org', 'retained_quarterly'
);

-- ============ pulse_checkins ============
-- Employee-submitted periodic check-in. EMPLOYEE OWNS THE DATA: every row
-- is is_self()-readable. Manager visibility requires has_permission +
-- in_scope + active ongoing_management consent. Never collected in the
-- background — the row only exists if the employee submitted it.
create table public.pulse_checkins (
  id           uuid primary key default extensions.gen_random_uuid(),
  org_id       uuid not null references public.organizations(id),
  person_id    uuid not null references public.people(id),
  consent_id   uuid not null references public.consent_grants(id),
  template_id  uuid references public.frameworks(id),
  submitted_at timestamptz not null default now(),
  body_json    jsonb not null default '{}'::jsonb,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index pulse_checkins_person_idx on public.pulse_checkins (person_id, submitted_at desc);

create trigger trg_touch_pulse_checkins  before update on public.pulse_checkins for each row execute function public.set_updated_at();
create trigger trg_audit_pulse_checkins  after insert or update or delete on public.pulse_checkins for each row execute function public._audit_row();

alter table public.pulse_checkins enable row level security;
alter table public.pulse_checkins force  row level security;

create policy pulse_checkins_select on public.pulse_checkins for select using (
  public.is_self(person_id)
  or (public.has_permission(org_id, 'pulse.read')
      and public.in_scope(org_id, person_id)
      and public.consent_active(consent_id, 'ongoing_management'))
);
create policy pulse_checkins_insert on public.pulse_checkins for insert with check (
  public.is_self(person_id) and public.consent_active(consent_id, 'ongoing_management')
);
-- UPDATE only by the data subject (developmental discipline — managers can't
-- silently mutate an employee's self-report).
create policy pulse_checkins_update on public.pulse_checkins for update
  using (public.is_self(person_id))
  with check (public.is_self(person_id));

-- ============ signals ============
-- Derived signals from pulses + structured profile data. Generated by RPC,
-- not collected in the background. The source_json field MUST cite the
-- structured data it was computed from (pulse_id, framework_id, etc.) so
-- the employee can see, on their self-view, exactly what fed each signal.
create table public.signals (
  id           uuid primary key default extensions.gen_random_uuid(),
  org_id       uuid not null references public.organizations(id),
  person_id    uuid not null references public.people(id),
  consent_id   uuid not null references public.consent_grants(id),
  kind         text not null,
  value_json   jsonb not null default '{}'::jsonb,
  source_json  jsonb not null default '{}'::jsonb,
  framework_id uuid references public.frameworks(id),
  generated_at timestamptz not null default now(),
  generated_by uuid references public.people(id),
  validity_status public.validity_status not null default 'dev_stub',
  _dev_stub    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint chk_signals_validated_real
    check (validity_status <> 'validated'
           or (value_json <> '{}'::jsonb and coalesce(_dev_stub, false) = false)),
  -- Developmental discipline: signal must cite its source structurally.
  constraint chk_signals_grounded
    check (source_json <> '{}'::jsonb)
);
create index signals_person_idx on public.signals (person_id, generated_at desc);

create trigger trg_touch_signals before update on public.signals for each row execute function public.set_updated_at();
create trigger trg_audit_signals after insert or update or delete on public.signals for each row execute function public._audit_row();

alter table public.signals enable row level security;
alter table public.signals force  row level security;

create policy signals_select on public.signals for select using (
  public.is_self(person_id)
  or (public.has_permission(org_id, 'pulse.read')
      and public.in_scope(org_id, person_id)
      and public.consent_active(consent_id, 'ongoing_management'))
);
create policy signals_insert on public.signals for insert with check (
  public.has_permission(org_id, 'pulse.read')
  and public.consent_active(consent_id, 'ongoing_management')
);

-- ============ refit_evaluations ============
-- Time-series of fit against the latest active role version. Each compute
-- APPENDS a new row — never overwrites. This is the "re-fit history" the
-- employee sees on their self-view.
create table public.refit_evaluations (
  id           uuid primary key default extensions.gen_random_uuid(),
  org_id       uuid not null references public.organizations(id),
  person_id    uuid not null references public.people(id),
  role_id      uuid not null references public.roles_catalog(id),
  consent_id   uuid not null references public.consent_grants(id),
  fit_json     jsonb not null,
  quadrant     public.refit_quadrant not null,
  validity_status public.validity_status not null default 'dev_stub',
  _dev_stub    boolean not null default true,
  computed_at  timestamptz not null default now(),
  computed_by  uuid references public.people(id),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint chk_refit_validated_real
    check (validity_status <> 'validated'
           or (fit_json <> '{}'::jsonb and coalesce(_dev_stub, false) = false))
);
create index refit_evaluations_person_idx on public.refit_evaluations (person_id, computed_at desc);

create trigger trg_touch_refit_evaluations before update on public.refit_evaluations for each row execute function public.set_updated_at();
create trigger trg_audit_refit_evaluations after insert or update or delete on public.refit_evaluations for each row execute function public._audit_row();

alter table public.refit_evaluations enable row level security;
alter table public.refit_evaluations force  row level security;

create policy refit_evaluations_select on public.refit_evaluations for select using (
  public.is_self(person_id)
  or (public.has_permission(org_id, 'refit.read')
      and public.in_scope(org_id, person_id)
      and public.consent_active(consent_id, 'ongoing_management'))
);
create policy refit_evaluations_insert on public.refit_evaluations for insert with check (
  public.has_permission(org_id, 'refit.compute')
  and public.consent_active(consent_id, 'ongoing_management')
);

-- ============ guidance_items ============
-- Manager-facing guidance. EVERY row MUST cite at least one framework_id —
-- enforced by the CHECK on framework_ids array length. inputs_json carries
-- the structured data that fed the generation (audit trail). action +
-- action_at let the manager record what they did with the guidance; the
-- suggestion INFORMS, never decides.
create table public.guidance_items (
  id              uuid primary key default extensions.gen_random_uuid(),
  org_id          uuid not null references public.organizations(id),
  person_id       uuid not null references public.people(id),
  consent_id      uuid not null references public.consent_grants(id),
  kind            public.guidance_kind not null,
  framework_ids   uuid[] not null,
  inputs_json     jsonb not null default '{}'::jsonb,
  output_json     jsonb not null,
  generated_at    timestamptz not null default now(),
  generated_by    uuid references public.people(id),
  action          public.guidance_action,
  action_at       timestamptz,
  action_notes    text,
  validity_status public.validity_status not null default 'dev_stub',
  _dev_stub       boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint chk_guidance_grounded check (array_length(framework_ids, 1) >= 1),
  constraint chk_guidance_validated_real
    check (validity_status <> 'validated'
           or (output_json <> '{}'::jsonb and coalesce(_dev_stub, false) = false))
);
create index guidance_items_person_idx on public.guidance_items (person_id, generated_at desc);

create trigger trg_touch_guidance_items before update on public.guidance_items for each row execute function public.set_updated_at();
create trigger trg_audit_guidance_items after insert or update or delete on public.guidance_items for each row execute function public._audit_row();

alter table public.guidance_items enable row level security;
alter table public.guidance_items force  row level security;

create policy guidance_items_select on public.guidance_items for select using (
  public.is_self(person_id)
  or (public.has_permission(org_id, 'guidance.read')
      and public.in_scope(org_id, person_id)
      and public.consent_active(consent_id, 'ongoing_management'))
);
create policy guidance_items_insert on public.guidance_items for insert with check (
  public.has_permission(org_id, 'guidance.generate')
  and public.consent_active(consent_id, 'ongoing_management')
);
-- The manager can record an action on a guidance row (acted_on / noted /
-- snoozed / dismissed) — but cannot mutate the generated output or its
-- framework citations.
create policy guidance_items_update on public.guidance_items for update
  using (public.has_permission(org_id, 'guidance.read')
         and public.in_scope(org_id, person_id)
         and public.consent_active(consent_id, 'ongoing_management'));

-- ============ growth_conversations ============
-- The 1:1 / structured-talk record. Manager-authored; consent-gated.
create table public.growth_conversations (
  id            uuid primary key default extensions.gen_random_uuid(),
  org_id        uuid not null references public.organizations(id),
  person_id     uuid not null references public.people(id),
  consent_id    uuid not null references public.consent_grants(id),
  conducted_by  uuid references public.people(id),
  happened_at   timestamptz not null default now(),
  topic         text,
  summary       text,
  framework_ids uuid[] not null default '{}',
  guidance_item_id uuid references public.guidance_items(id),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index growth_conversations_person_idx on public.growth_conversations (person_id, happened_at desc);

create trigger trg_touch_growth_conversations before update on public.growth_conversations for each row execute function public.set_updated_at();
create trigger trg_audit_growth_conversations after insert or update or delete on public.growth_conversations for each row execute function public._audit_row();

alter table public.growth_conversations enable row level security;
alter table public.growth_conversations force  row level security;

create policy growth_conversations_select on public.growth_conversations for select using (
  public.is_self(person_id)
  or (public.has_permission(org_id, 'guidance.read')
      and public.in_scope(org_id, person_id)
      and public.consent_active(consent_id, 'ongoing_management'))
);
create policy growth_conversations_insert on public.growth_conversations for insert with check (
  public.has_permission(org_id, 'guidance.read')
  and public.consent_active(consent_id, 'ongoing_management')
);

-- ============ team_composition_snapshots ============
-- Aggregate strengths/gaps for a team. Source: members' OWN profiles
-- (subject to each member's ongoing_management consent). NEVER peer
-- ratings of each other's personalities — hard rule from CLAUDE.md.
create table public.team_composition_snapshots (
  id            uuid primary key default extensions.gen_random_uuid(),
  org_id        uuid not null references public.organizations(id),
  team_id       uuid not null references public.teams(id),
  snapshot_json jsonb not null,
  members_consented int not null default 0,   -- how many team members contributed
  members_total     int not null default 0,
  generated_at  timestamptz not null default now(),
  generated_by  uuid references public.people(id),
  validity_status public.validity_status not null default 'dev_stub',
  _dev_stub     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint chk_team_composition_validated_real
    check (validity_status <> 'validated'
           or (snapshot_json <> '{}'::jsonb and coalesce(_dev_stub, false) = false))
);
create index team_composition_team_idx on public.team_composition_snapshots (team_id, generated_at desc);

create trigger trg_touch_team_composition before update on public.team_composition_snapshots for each row execute function public.set_updated_at();
create trigger trg_audit_team_composition after insert or update or delete on public.team_composition_snapshots for each row execute function public._audit_row();

alter table public.team_composition_snapshots enable row level security;
alter table public.team_composition_snapshots force  row level security;

create policy team_composition_select on public.team_composition_snapshots for select using (
  public.has_permission(org_id, 'team.read')
);
create policy team_composition_insert on public.team_composition_snapshots for insert with check (
  public.has_permission(org_id, 'team.read')
);

-- ============ outcome_captures ============
-- Outcomes RECORDED, not modeled. Phase 3 stores what actually happened
-- (promoted / lateral / left / etc.) so future phases can LEARN from
-- ground truth. No prediction algorithms here.
create table public.outcome_captures (
  id           uuid primary key default extensions.gen_random_uuid(),
  org_id       uuid not null references public.organizations(id),
  person_id    uuid not null references public.people(id),
  consent_id   uuid not null references public.consent_grants(id),
  kind         public.outcome_kind not null,
  happened_at  date not null,
  notes        text,
  captured_by  uuid references public.people(id),
  captured_at  timestamptz not null default now(),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index outcome_captures_person_idx on public.outcome_captures (person_id, happened_at desc);

create trigger trg_touch_outcome_captures before update on public.outcome_captures for each row execute function public.set_updated_at();
create trigger trg_audit_outcome_captures after insert or update or delete on public.outcome_captures for each row execute function public._audit_row();

alter table public.outcome_captures enable row level security;
alter table public.outcome_captures force  row level security;

create policy outcome_captures_select on public.outcome_captures for select using (
  public.is_self(person_id)
  or (public.has_permission(org_id, 'org.read')
      and public.in_scope(org_id, person_id)
      and public.consent_active(consent_id, 'ongoing_management'))
);
create policy outcome_captures_insert on public.outcome_captures for insert with check (
  public.has_permission(org_id, 'org.manage_all')
  and public.consent_active(consent_id, 'ongoing_management')
);

-- ============ Permissions ============
-- Add the Phase 3 permission keys. Grant the appropriate role × permission
-- pairs so the seeded users can actually use the new surfaces.
insert into public.rbac_permissions (key, description) values
  ('pulse.read',         'Read pulse_checkins and signals for in-scope people (consent-gated)'),
  ('refit.read',         'Read refit_evaluations for in-scope people (consent-gated)'),
  ('refit.compute',      'Compute a re-fit evaluation (writes refit_evaluations)'),
  ('guidance.read',      'Read guidance_items + growth_conversations (consent-gated)'),
  ('guidance.generate',  'Generate guidance_items via the composer'),
  ('team.read',          'Read team_composition_snapshots')
on conflict (key) do nothing;

-- Grant the new permissions to org_admin (everything) + people_ops_admin
-- (operational) + manager (their reports). Recruiter does NOT get any
-- of these — recruiter scope ends at placement.
insert into public.rbac_role_permissions (role_id, permission_id)
select r.id, p.id
  from public.rbac_roles r
  cross join public.rbac_permissions p
  where r.org_id is null
    and r.key in ('org_admin','people_ops_admin')
    and p.key in ('pulse.read','refit.read','refit.compute','guidance.read','guidance.generate','team.read')
on conflict do nothing;

insert into public.rbac_role_permissions (role_id, permission_id)
select r.id, p.id
  from public.rbac_roles r
  cross join public.rbac_permissions p
  where r.org_id is null
    and r.key = 'manager'
    and p.key in ('pulse.read','refit.read','refit.compute','guidance.read','guidance.generate','team.read')
on conflict do nothing;

-- The data subject (employee role) gets read-only on their own data via
-- is_self() RLS predicates — no extra permission grant needed.

-- ============ Module registration ============
insert into public.modules (key, name, status, config_schema_json) values
  ('lifecycle', 'Lifecycle (Phase 3 — manager + employee)', 'beta',
    '{"type":"object","properties":{"refit_cadence_days":{"type":"integer","minimum":7}}}'::jsonb)
on conflict (key) do nothing;
-- Enable for both seeded orgs.
insert into public.org_modules (org_id, module_key, enabled, config_json)
select id, 'lifecycle', true, '{}'::jsonb
  from public.organizations
  where id in ('a1000000-0000-0000-0000-000000000001'::uuid,
               'a1000000-0000-0000-0000-000000000002'::uuid)
on conflict (org_id, module_key) do update set enabled = true;
